CREATE TABLE [dbo].[mail_Cuentas_Correo] (
    [IdCuenta]                                VARCHAR (50)  NOT NULL,
    [Nombre_cuenta]                           VARCHAR (150) NULL,
    [direccion_correo]                        VARCHAR (150) NULL,
    [Usuario]                                 VARCHAR (50)  NOT NULL,
    [Password]                                VARCHAR (50)  NOT NULL,
    [TipoCuenta]                              VARCHAR (50)  NOT NULL,
    [ServidorCorreoEntrante]                  VARCHAR (150) NULL,
    [ServidorCorreoSaliente]                  VARCHAR (150) NULL,
    [Port_salida]                             INT           NOT NULL,
    [port_entrada]                            INT           NOT NULL,
    [cta_predeterminada]                      BIT           NOT NULL,
    [tipo_Seguridad]                          VARCHAR (50)  NULL,
    [precisa_conexion_cifrada]                BIT           NULL,
    [enviar_copia_x_cada_mail_enviado]        BIT           NULL,
    [enviar_mail_x_cada_cbte_no_auto]         BIT           NULL,
    [cta_mail_para_envio_x_cbte_enviado]      VARCHAR (150) NULL,
    [cta_mail_para_envio_x_cbte_no_auto]      VARCHAR (150) NULL,
    [Usar_Credenciales_x_default_SMTP]        BIT           NULL,
    [Tipo_Authenticacion]                     VARCHAR (50)  NULL,
    [Usa_SSL_Conexion_para_Descarga_correo]   BIT           NULL,
    [Guardar_1_copia_de_corre_en_server_mail] BIT           NULL,
    [Borra_server_mail_cada_dias]             INT           NULL,
    [Usuario_smtp]                            VARCHAR (50)  NULL,
    [Password_smtp]                           VARCHAR (50)  NULL,
    [Confirmacion_de_Lectura]                 BIT           NULL,
    [Confirmacion_de_Entrega]                 BIT           NULL,
    CONSTRAINT [PK_Mail_Cuentas_Correo] PRIMARY KEY CLUSTERED ([IdCuenta] ASC)
);

