CREATE TABLE [dbo].[tb_Comprobante] (
    [IdEmpresa]           INT           NOT NULL,
    [IdComprobante]       VARCHAR (100) NOT NULL,
    [IdTipoDocumento]     VARCHAR (10)  NOT NULL,
    [IdEstado_cbte]       VARCHAR (25)  NOT NULL,
    [Cedula_Ruc]          VARCHAR (20)  NULL,
    [Numero_Autorizacion] VARCHAR (200) NULL,
    [RutaArchivo]         VARCHAR (MAX) NULL,
    [Nombre_file]         VARCHAR (250) NULL,
    [s_XML]               VARCHAR (MAX) NULL,
    [Fecha_Emi_Fact]      DATETIME      NULL,
    [Fecha_transaccion]   DATETIME      NULL,
    [FechaAutorizacion]   DATETIME      NULL,
    [ClaveContingencia]   VARCHAR (50)  NULL,
    [EstadoDoc]           VARCHAR (50)  NULL,
    [Error]               VARCHAR (MAX) NULL,
    [IdEstadoProceso]     VARCHAR (15)  NOT NULL,
    [IdError_Sri]         VARCHAR (25)  NULL,
    [RespuestaSRI]        VARCHAR (MAX) NULL,
    [Total]               FLOAT (53)    NULL,
    [Ambiente]            VARCHAR (20)  NULL,
    [s_xml_bak]           VARCHAR (MAX) NULL,
    [Clave_Acceso]        VARCHAR (100) NULL,
    CONSTRAINT [PK_tb_Comprobante_1] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdComprobante] ASC, [IdTipoDocumento] ASC, [IdEstado_cbte] ASC),
    CONSTRAINT [FK_tb_Comprobante_tb_Catalogo1] FOREIGN KEY ([IdTipoDocumento]) REFERENCES [dbo].[tb_Catalogo] ([IdCatalogo]),
    CONSTRAINT [FK_tb_Comprobante_tb_Comprobante_estado_proceso] FOREIGN KEY ([IdEstadoProceso]) REFERENCES [dbo].[tb_Comprobante_estado_proceso] ([IdEstadoProceso]),
    CONSTRAINT [FK_tb_Comprobante_tb_Comprobante_tipo_estado] FOREIGN KEY ([IdEstado_cbte]) REFERENCES [dbo].[tb_Comprobante_tipo_estado] ([IdEstado_cbte]),
    CONSTRAINT [FK_tb_Comprobante_tb_Empresa] FOREIGN KEY ([IdEmpresa]) REFERENCES [dbo].[tb_Empresa] ([IdEmpresa])
);

