CREATE TABLE [dbo].[tb_Comprobante_Hist_Eliminado] (
    [IdEmpresa]            INT           NOT NULL,
    [IdComprobante]        VARCHAR (100) NOT NULL,
    [IdTipoDocumento]      VARCHAR (10)  NOT NULL,
    [IdEstado_cbte]        VARCHAR (25)  NOT NULL,
    [Secuencial]           NUMERIC (18)  NOT NULL,
    [Cedula_Ruc]           VARCHAR (20)  NULL,
    [Numero_Autorizacion]  VARCHAR (200) NULL,
    [RutaArchivo]          VARCHAR (MAX) NULL,
    [Nombre_file]          VARCHAR (250) NULL,
    [s_XML]                VARCHAR (MAX) NULL,
    [Fecha_Emi_Fact]       DATETIME      NULL,
    [Fecha_transaccion]    DATETIME      NULL,
    [FechaAutorizacion]    DATETIME      NULL,
    [ClaveContingencia]    VARCHAR (50)  NULL,
    [EstadoDoc]            VARCHAR (50)  NULL,
    [Error]                VARCHAR (MAX) NULL,
    [IdEstadoProceso]      VARCHAR (15)  NOT NULL,
    [IdError_Sri]          VARCHAR (25)  NULL,
    [RespuestaSRI]         VARCHAR (MAX) NULL,
    [Total]                FLOAT (53)    NULL,
    [Usuario_Anulo]        VARCHAR (50)  NULL,
    [Fecha_hora_anulacion] DATETIME      NULL,
    [IpAnulacion]          VARCHAR (50)  NULL,
    [Motivo_Anulacion]     VARCHAR (150) NULL,
    [Clave_Acceso]         VARCHAR (100) NULL,
    [Ambiente]             VARCHAR (20)  NULL,
    CONSTRAINT [PK_tb_Comprobante_Hist_Eliminado] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC, [IdComprobante] ASC, [IdTipoDocumento] ASC, [IdEstado_cbte] ASC, [Secuencial] ASC)
);

