CREATE TABLE [dbo].[tb_Empresa] (
    [IdEmpresa]                   INT           NOT NULL,
    [RazonSocial]                 VARCHAR (300) NOT NULL,
    [NombreComercial]             VARCHAR (300) NOT NULL,
    [RUC]                         VARCHAR (13)  NOT NULL,
    [DirMatriz]                   VARCHAR (300) NOT NULL,
    [ContribuyenteEspecial]       VARCHAR (5)   NOT NULL,
    [ObligadoAllevarConta]        VARCHAR (2)   NOT NULL,
    [NombreCertificado]           VARCHAR (200) NULL,
    [Clave_Certificado]           VARCHAR (150) NOT NULL,
    [FechaValidez]                DATETIME      NULL,
    [Estado]                      BIT           NOT NULL,
    [logo]                        IMAGE         NULL,
    [Alias]                       VARCHAR (100) NULL,
    [IdToquenAFirmar]             VARCHAR (10)  NULL,
    [cod_Ambiente]                VARCHAR (10)  NOT NULL,
    [cod_TipoEmision]             VARCHAR (10)  NOT NULL,
    [url]                         VARCHAR (50)  NULL,
    [Tipo_Notificacion_a_cliente] VARCHAR (20)  NULL,
    [Nemonico_RIDE]               VARCHAR (5)   NULL,
    [Tipo_Base_Exterior]          VARCHAR (20)  NULL,
    [cadena_conexion_Exterior]    VARCHAR (500) NULL,
    [Cod_Empresa_Para_DB_Ext]     VARCHAR (20)  NULL,
    [Formato_fecha_Base_ext]      VARCHAR (20)  NULL,
    [Formato_hora_Base_ext]       VARCHAR (20)  NULL,
    [Nombre_tabla_Base_ext]       VARCHAR (50)  NULL,
    CONSTRAINT [PK_tb_Empresa] PRIMARY KEY CLUSTERED ([IdEmpresa] ASC)
);

