CREATE TABLE [dbo].[tb_FormaPago](
	[IdFormaPago] [varchar](2) NOT NULL,
	[nombre] [varchar](500) NOT NULL,
 CONSTRAINT [PK_tb_FormaPago] PRIMARY KEY CLUSTERED 
(
	[IdFormaPago] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
