//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efirm.WSEfirm_Contribuyente {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEfirm_Contribuyente.IWs_Contribuyente")]
    public interface IWs_Contribuyente {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/GetContribuyente", ReplyAction="http://tempuri.org/IWs_Contribuyente/GetContribuyenteResponse")]
        Efirm.WSEfirm_Contribuyente.GetContribuyenteResponse GetContribuyente(Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/GetContribuyente", ReplyAction="http://tempuri.org/IWs_Contribuyente/GetContribuyenteResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.GetContribuyenteResponse> GetContribuyenteAsync(Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/GetContribuyente_Info", ReplyAction="http://tempuri.org/IWs_Contribuyente/GetContribuyente_InfoResponse")]
        Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoResponse GetContribuyente_Info(Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/GetContribuyente_Info", ReplyAction="http://tempuri.org/IWs_Contribuyente/GetContribuyente_InfoResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoResponse> GetContribuyente_InfoAsync(Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/Modificar_GetContribuyente_Info", ReplyAction="http://tempuri.org/IWs_Contribuyente/Modificar_GetContribuyente_InfoResponse")]
        Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoResponse Modificar_GetContribuyente_Info(Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Contribuyente/Modificar_GetContribuyente_Info", ReplyAction="http://tempuri.org/IWs_Contribuyente/Modificar_GetContribuyente_InfoResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoResponse> Modificar_GetContribuyente_InfoAsync(Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContribuyente", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContribuyenteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedulaRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string MensajeErrorOut;
        
        public GetContribuyenteRequest() {
        }
        
        public GetContribuyenteRequest(int IdEmpresa, string cedulaRuc, string password, string MensajeErrorOut) {
            this.IdEmpresa = IdEmpresa;
            this.cedulaRuc = cedulaRuc;
            this.password = password;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContribuyenteResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContribuyenteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Contribuyente_Info[] GetContribuyenteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetContribuyenteResponse() {
        }
        
        public GetContribuyenteResponse(FirmElect.Info.tb_Contribuyente_Info[] GetContribuyenteResult, string MensajeErrorOut) {
            this.GetContribuyenteResult = GetContribuyenteResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContribuyente_Info", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContribuyente_InfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedulaRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string MensajeErrorOut;
        
        public GetContribuyente_InfoRequest() {
        }
        
        public GetContribuyente_InfoRequest(int IdEmpresa, string cedulaRuc, string MensajeErrorOut) {
            this.IdEmpresa = IdEmpresa;
            this.cedulaRuc = cedulaRuc;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetContribuyente_InfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetContribuyente_InfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Contribuyente_Info GetContribuyente_InfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetContribuyente_InfoResponse() {
        }
        
        public GetContribuyente_InfoResponse(FirmElect.Info.tb_Contribuyente_Info GetContribuyente_InfoResult, string MensajeErrorOut) {
            this.GetContribuyente_InfoResult = GetContribuyente_InfoResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_GetContribuyente_Info", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modificar_GetContribuyente_InfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedulaRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string mail;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string password;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public string MensajeErrorOut;
        
        public Modificar_GetContribuyente_InfoRequest() {
        }
        
        public Modificar_GetContribuyente_InfoRequest(int IdEmpresa, string cedulaRuc, string mail, string password, string MensajeErrorOut) {
            this.IdEmpresa = IdEmpresa;
            this.cedulaRuc = cedulaRuc;
            this.mail = mail;
            this.password = password;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Modificar_GetContribuyente_InfoResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Modificar_GetContribuyente_InfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool Modificar_GetContribuyente_InfoResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public Modificar_GetContribuyente_InfoResponse() {
        }
        
        public Modificar_GetContribuyente_InfoResponse(bool Modificar_GetContribuyente_InfoResult, string MensajeErrorOut) {
            this.Modificar_GetContribuyente_InfoResult = Modificar_GetContribuyente_InfoResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWs_ContribuyenteChannel : Efirm.WSEfirm_Contribuyente.IWs_Contribuyente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_ContribuyenteClient : System.ServiceModel.ClientBase<Efirm.WSEfirm_Contribuyente.IWs_Contribuyente>, Efirm.WSEfirm_Contribuyente.IWs_Contribuyente {
        
        public Ws_ContribuyenteClient() {
        }
        
        public Ws_ContribuyenteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_ContribuyenteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_ContribuyenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_ContribuyenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Contribuyente.GetContribuyenteResponse Efirm.WSEfirm_Contribuyente.IWs_Contribuyente.GetContribuyente(Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest request) {
            return base.Channel.GetContribuyente(request);
        }
        
        public FirmElect.Info.tb_Contribuyente_Info[] GetContribuyente(int IdEmpresa, string cedulaRuc, string password, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest inValue = new Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest();
            inValue.IdEmpresa = IdEmpresa;
            inValue.cedulaRuc = cedulaRuc;
            inValue.password = password;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Contribuyente.GetContribuyenteResponse retVal = ((Efirm.WSEfirm_Contribuyente.IWs_Contribuyente)(this)).GetContribuyente(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GetContribuyenteResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.GetContribuyenteResponse> GetContribuyenteAsync(Efirm.WSEfirm_Contribuyente.GetContribuyenteRequest request) {
            return base.Channel.GetContribuyenteAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoResponse Efirm.WSEfirm_Contribuyente.IWs_Contribuyente.GetContribuyente_Info(Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest request) {
            return base.Channel.GetContribuyente_Info(request);
        }
        
        public FirmElect.Info.tb_Contribuyente_Info GetContribuyente_Info(int IdEmpresa, string cedulaRuc, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest inValue = new Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest();
            inValue.IdEmpresa = IdEmpresa;
            inValue.cedulaRuc = cedulaRuc;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoResponse retVal = ((Efirm.WSEfirm_Contribuyente.IWs_Contribuyente)(this)).GetContribuyente_Info(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GetContribuyente_InfoResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoResponse> GetContribuyente_InfoAsync(Efirm.WSEfirm_Contribuyente.GetContribuyente_InfoRequest request) {
            return base.Channel.GetContribuyente_InfoAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoResponse Efirm.WSEfirm_Contribuyente.IWs_Contribuyente.Modificar_GetContribuyente_Info(Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest request) {
            return base.Channel.Modificar_GetContribuyente_Info(request);
        }
        
        public bool Modificar_GetContribuyente_Info(int IdEmpresa, string cedulaRuc, string mail, string password, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest inValue = new Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest();
            inValue.IdEmpresa = IdEmpresa;
            inValue.cedulaRuc = cedulaRuc;
            inValue.mail = mail;
            inValue.password = password;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoResponse retVal = ((Efirm.WSEfirm_Contribuyente.IWs_Contribuyente)(this)).Modificar_GetContribuyente_Info(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.Modificar_GetContribuyente_InfoResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoResponse> Modificar_GetContribuyente_InfoAsync(Efirm.WSEfirm_Contribuyente.Modificar_GetContribuyente_InfoRequest request) {
            return base.Channel.Modificar_GetContribuyente_InfoAsync(request);
        }
    }
}
