//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efirm.WSEfirm_cbte {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEfirm_cbte.IWs_Comprobante")]
    public interface IWs_Comprobante {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/Lista_TipoComprobantes", ReplyAction="http://tempuri.org/IWs_Comprobante/Lista_TipoComprobantesResponse")]
        Efirm.WSEfirm_cbte.Lista_TipoComprobantesResponse Lista_TipoComprobantes(Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/Lista_TipoComprobantes", ReplyAction="http://tempuri.org/IWs_Comprobante/Lista_TipoComprobantesResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.Lista_TipoComprobantesResponse> Lista_TipoComprobantesAsync(Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/consultar_listado_comprobantes", ReplyAction="http://tempuri.org/IWs_Comprobante/consultar_listado_comprobantesResponse")]
        Efirm.WSEfirm_cbte.consultar_listado_comprobantesResponse consultar_listado_comprobantes(Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/consultar_listado_comprobantes", ReplyAction="http://tempuri.org/IWs_Comprobante/consultar_listado_comprobantesResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.consultar_listado_comprobantesResponse> consultar_listado_comprobantesAsync(Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/getXML", ReplyAction="http://tempuri.org/IWs_Comprobante/getXMLResponse")]
        Efirm.WSEfirm_cbte.getXMLResponse getXML(Efirm.WSEfirm_cbte.getXMLRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/getXML", ReplyAction="http://tempuri.org/IWs_Comprobante/getXMLResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.getXMLResponse> getXMLAsync(Efirm.WSEfirm_cbte.getXMLRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/getRide_Pdf", ReplyAction="http://tempuri.org/IWs_Comprobante/getRide_PdfResponse")]
        byte[] getRide_Pdf(int IdEmpresa, string cedulaRuc, string IdComprobante);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Comprobante/getRide_Pdf", ReplyAction="http://tempuri.org/IWs_Comprobante/getRide_PdfResponse")]
        System.Threading.Tasks.Task<byte[]> getRide_PdfAsync(int IdEmpresa, string cedulaRuc, string IdComprobante);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lista_TipoComprobantes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Lista_TipoComprobantesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MensajeErrorOut;
        
        public Lista_TipoComprobantesRequest() {
        }
        
        public Lista_TipoComprobantesRequest(string MensajeErrorOut) {
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Lista_TipoComprobantesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class Lista_TipoComprobantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Catalogo_Info[] Lista_TipoComprobantesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public Lista_TipoComprobantesResponse() {
        }
        
        public Lista_TipoComprobantesResponse(FirmElect.Info.tb_Catalogo_Info[] Lista_TipoComprobantesResult, string MensajeErrorOut) {
            this.Lista_TipoComprobantesResult = Lista_TipoComprobantesResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_listado_comprobantes", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class consultar_listado_comprobantesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedulaRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string TipoComprobante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public System.DateTime FecIni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=4)]
        public System.DateTime FecFin;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=5)]
        public string buscar;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=6)]
        public int Indice_Pagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=7)]
        public int Tamanio_Pagina;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=8)]
        public string mensajeErrorOut;
        
        public consultar_listado_comprobantesRequest() {
        }
        
        public consultar_listado_comprobantesRequest(int IdEmpresa, string cedulaRuc, string TipoComprobante, System.DateTime FecIni, System.DateTime FecFin, string buscar, int Indice_Pagina, int Tamanio_Pagina, string mensajeErrorOut) {
            this.IdEmpresa = IdEmpresa;
            this.cedulaRuc = cedulaRuc;
            this.TipoComprobante = TipoComprobante;
            this.FecIni = FecIni;
            this.FecFin = FecFin;
            this.buscar = buscar;
            this.Indice_Pagina = Indice_Pagina;
            this.Tamanio_Pagina = Tamanio_Pagina;
            this.mensajeErrorOut = mensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="consultar_listado_comprobantesResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class consultar_listado_comprobantesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Comprobante_Info[] consultar_listado_comprobantesResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensajeErrorOut;
        
        public consultar_listado_comprobantesResponse() {
        }
        
        public consultar_listado_comprobantesResponse(FirmElect.Info.tb_Comprobante_Info[] consultar_listado_comprobantesResult, string mensajeErrorOut) {
            this.consultar_listado_comprobantesResult = consultar_listado_comprobantesResult;
            this.mensajeErrorOut = mensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXML", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getXMLRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int IdEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string cedulaRuc;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=2)]
        public string IdComprobante;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=3)]
        public string mensajeErrorOut;
        
        public getXMLRequest() {
        }
        
        public getXMLRequest(int IdEmpresa, string cedulaRuc, string IdComprobante, string mensajeErrorOut) {
            this.IdEmpresa = IdEmpresa;
            this.cedulaRuc = cedulaRuc;
            this.IdComprobante = IdComprobante;
            this.mensajeErrorOut = mensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getXMLResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class getXMLResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string getXMLResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string mensajeErrorOut;
        
        public getXMLResponse() {
        }
        
        public getXMLResponse(string getXMLResult, string mensajeErrorOut) {
            this.getXMLResult = getXMLResult;
            this.mensajeErrorOut = mensajeErrorOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWs_ComprobanteChannel : Efirm.WSEfirm_cbte.IWs_Comprobante, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_ComprobanteClient : System.ServiceModel.ClientBase<Efirm.WSEfirm_cbte.IWs_Comprobante>, Efirm.WSEfirm_cbte.IWs_Comprobante {
        
        public Ws_ComprobanteClient() {
        }
        
        public Ws_ComprobanteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_ComprobanteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_ComprobanteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_ComprobanteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_cbte.Lista_TipoComprobantesResponse Efirm.WSEfirm_cbte.IWs_Comprobante.Lista_TipoComprobantes(Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest request) {
            return base.Channel.Lista_TipoComprobantes(request);
        }
        
        public FirmElect.Info.tb_Catalogo_Info[] Lista_TipoComprobantes(ref string MensajeErrorOut) {
            Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest inValue = new Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest();
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_cbte.Lista_TipoComprobantesResponse retVal = ((Efirm.WSEfirm_cbte.IWs_Comprobante)(this)).Lista_TipoComprobantes(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.Lista_TipoComprobantesResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.Lista_TipoComprobantesResponse> Lista_TipoComprobantesAsync(Efirm.WSEfirm_cbte.Lista_TipoComprobantesRequest request) {
            return base.Channel.Lista_TipoComprobantesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_cbte.consultar_listado_comprobantesResponse Efirm.WSEfirm_cbte.IWs_Comprobante.consultar_listado_comprobantes(Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest request) {
            return base.Channel.consultar_listado_comprobantes(request);
        }
        
        public FirmElect.Info.tb_Comprobante_Info[] consultar_listado_comprobantes(int IdEmpresa, string cedulaRuc, string TipoComprobante, System.DateTime FecIni, System.DateTime FecFin, string buscar, int Indice_Pagina, int Tamanio_Pagina, ref string mensajeErrorOut) {
            Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest inValue = new Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest();
            inValue.IdEmpresa = IdEmpresa;
            inValue.cedulaRuc = cedulaRuc;
            inValue.TipoComprobante = TipoComprobante;
            inValue.FecIni = FecIni;
            inValue.FecFin = FecFin;
            inValue.buscar = buscar;
            inValue.Indice_Pagina = Indice_Pagina;
            inValue.Tamanio_Pagina = Tamanio_Pagina;
            inValue.mensajeErrorOut = mensajeErrorOut;
            Efirm.WSEfirm_cbte.consultar_listado_comprobantesResponse retVal = ((Efirm.WSEfirm_cbte.IWs_Comprobante)(this)).consultar_listado_comprobantes(inValue);
            mensajeErrorOut = retVal.mensajeErrorOut;
            return retVal.consultar_listado_comprobantesResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.consultar_listado_comprobantesResponse> consultar_listado_comprobantesAsync(Efirm.WSEfirm_cbte.consultar_listado_comprobantesRequest request) {
            return base.Channel.consultar_listado_comprobantesAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_cbte.getXMLResponse Efirm.WSEfirm_cbte.IWs_Comprobante.getXML(Efirm.WSEfirm_cbte.getXMLRequest request) {
            return base.Channel.getXML(request);
        }
        
        public string getXML(int IdEmpresa, string cedulaRuc, string IdComprobante, ref string mensajeErrorOut) {
            Efirm.WSEfirm_cbte.getXMLRequest inValue = new Efirm.WSEfirm_cbte.getXMLRequest();
            inValue.IdEmpresa = IdEmpresa;
            inValue.cedulaRuc = cedulaRuc;
            inValue.IdComprobante = IdComprobante;
            inValue.mensajeErrorOut = mensajeErrorOut;
            Efirm.WSEfirm_cbte.getXMLResponse retVal = ((Efirm.WSEfirm_cbte.IWs_Comprobante)(this)).getXML(inValue);
            mensajeErrorOut = retVal.mensajeErrorOut;
            return retVal.getXMLResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_cbte.getXMLResponse> getXMLAsync(Efirm.WSEfirm_cbte.getXMLRequest request) {
            return base.Channel.getXMLAsync(request);
        }
        
        public byte[] getRide_Pdf(int IdEmpresa, string cedulaRuc, string IdComprobante) {
            return base.Channel.getRide_Pdf(IdEmpresa, cedulaRuc, IdComprobante);
        }
        
        public System.Threading.Tasks.Task<byte[]> getRide_PdfAsync(int IdEmpresa, string cedulaRuc, string IdComprobante) {
            return base.Channel.getRide_PdfAsync(IdEmpresa, cedulaRuc, IdComprobante);
        }
    }
}
