//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18063
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Efirm.WSEfirm_Empresa {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WSEfirm_Empresa.IWs_Empresa")]
    public interface IWs_Empresa {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresasResponse")]
        Efirm.WSEfirm_Empresa.GetEmpresasResponse GetEmpresas(Efirm.WSEfirm_Empresa.GetEmpresasRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresasResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresasResponse> GetEmpresasAsync(Efirm.WSEfirm_Empresa.GetEmpresasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GrabarDB", ReplyAction="http://tempuri.org/IWs_Empresa/GrabarDBResponse")]
        Efirm.WSEfirm_Empresa.GrabarDBResponse GrabarDB(Efirm.WSEfirm_Empresa.GrabarDBRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GrabarDB", ReplyAction="http://tempuri.org/IWs_Empresa/GrabarDBResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GrabarDBResponse> GrabarDBAsync(Efirm.WSEfirm_Empresa.GrabarDBRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas_x_Alias", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresas_x_AliasResponse")]
        Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasResponse GetEmpresas_x_Alias(Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas_x_Alias", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresas_x_AliasResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasResponse> GetEmpresas_x_AliasAsync(Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas_x_Url", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresas_x_UrlResponse")]
        Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlResponse GetEmpresas_x_Url(Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWs_Empresa/GetEmpresas_x_Url", ReplyAction="http://tempuri.org/IWs_Empresa/GetEmpresas_x_UrlResponse")]
        System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlResponse> GetEmpresas_x_UrlAsync(Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresas", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string MensajeErrorOut;
        
        public GetEmpresasRequest() {
        }
        
        public GetEmpresasRequest(string MensajeErrorOut) {
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresasResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetEmpresasResponse() {
        }
        
        public GetEmpresasResponse(FirmElect.Info.tb_Empresa_Info[] GetEmpresasResult, string MensajeErrorOut) {
            this.GetEmpresasResult = GetEmpresasResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GrabarDB", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GrabarDBRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Empresa_Info InfoEmpresa;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GrabarDBRequest() {
        }
        
        public GrabarDBRequest(FirmElect.Info.tb_Empresa_Info InfoEmpresa, string MensajeErrorOut) {
            this.InfoEmpresa = InfoEmpresa;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GrabarDBResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GrabarDBResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public bool GrabarDBResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GrabarDBResponse() {
        }
        
        public GrabarDBResponse(bool GrabarDBResult, string MensajeErrorOut) {
            this.GrabarDBResult = GrabarDBResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresas_x_Alias", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresas_x_AliasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string alias;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetEmpresas_x_AliasRequest() {
        }
        
        public GetEmpresas_x_AliasRequest(string alias, string MensajeErrorOut) {
            this.alias = alias;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresas_x_AliasResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresas_x_AliasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_AliasResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetEmpresas_x_AliasResponse() {
        }
        
        public GetEmpresas_x_AliasResponse(FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_AliasResult, string MensajeErrorOut) {
            this.GetEmpresas_x_AliasResult = GetEmpresas_x_AliasResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresas_x_Url", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresas_x_UrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string url;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetEmpresas_x_UrlRequest() {
        }
        
        public GetEmpresas_x_UrlRequest(string url, string MensajeErrorOut) {
            this.url = url;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEmpresas_x_UrlResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEmpresas_x_UrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_UrlResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=1)]
        public string MensajeErrorOut;
        
        public GetEmpresas_x_UrlResponse() {
        }
        
        public GetEmpresas_x_UrlResponse(FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_UrlResult, string MensajeErrorOut) {
            this.GetEmpresas_x_UrlResult = GetEmpresas_x_UrlResult;
            this.MensajeErrorOut = MensajeErrorOut;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWs_EmpresaChannel : Efirm.WSEfirm_Empresa.IWs_Empresa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Ws_EmpresaClient : System.ServiceModel.ClientBase<Efirm.WSEfirm_Empresa.IWs_Empresa>, Efirm.WSEfirm_Empresa.IWs_Empresa {
        
        public Ws_EmpresaClient() {
        }
        
        public Ws_EmpresaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Ws_EmpresaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_EmpresaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Ws_EmpresaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Empresa.GetEmpresasResponse Efirm.WSEfirm_Empresa.IWs_Empresa.GetEmpresas(Efirm.WSEfirm_Empresa.GetEmpresasRequest request) {
            return base.Channel.GetEmpresas(request);
        }
        
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresas(ref string MensajeErrorOut) {
            Efirm.WSEfirm_Empresa.GetEmpresasRequest inValue = new Efirm.WSEfirm_Empresa.GetEmpresasRequest();
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Empresa.GetEmpresasResponse retVal = ((Efirm.WSEfirm_Empresa.IWs_Empresa)(this)).GetEmpresas(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GetEmpresasResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresasResponse> GetEmpresasAsync(Efirm.WSEfirm_Empresa.GetEmpresasRequest request) {
            return base.Channel.GetEmpresasAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Empresa.GrabarDBResponse Efirm.WSEfirm_Empresa.IWs_Empresa.GrabarDB(Efirm.WSEfirm_Empresa.GrabarDBRequest request) {
            return base.Channel.GrabarDB(request);
        }
        
        public bool GrabarDB(FirmElect.Info.tb_Empresa_Info InfoEmpresa, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Empresa.GrabarDBRequest inValue = new Efirm.WSEfirm_Empresa.GrabarDBRequest();
            inValue.InfoEmpresa = InfoEmpresa;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Empresa.GrabarDBResponse retVal = ((Efirm.WSEfirm_Empresa.IWs_Empresa)(this)).GrabarDB(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GrabarDBResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GrabarDBResponse> GrabarDBAsync(Efirm.WSEfirm_Empresa.GrabarDBRequest request) {
            return base.Channel.GrabarDBAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasResponse Efirm.WSEfirm_Empresa.IWs_Empresa.GetEmpresas_x_Alias(Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest request) {
            return base.Channel.GetEmpresas_x_Alias(request);
        }
        
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_Alias(string alias, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest inValue = new Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest();
            inValue.alias = alias;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasResponse retVal = ((Efirm.WSEfirm_Empresa.IWs_Empresa)(this)).GetEmpresas_x_Alias(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GetEmpresas_x_AliasResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasResponse> GetEmpresas_x_AliasAsync(Efirm.WSEfirm_Empresa.GetEmpresas_x_AliasRequest request) {
            return base.Channel.GetEmpresas_x_AliasAsync(request);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlResponse Efirm.WSEfirm_Empresa.IWs_Empresa.GetEmpresas_x_Url(Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest request) {
            return base.Channel.GetEmpresas_x_Url(request);
        }
        
        public FirmElect.Info.tb_Empresa_Info[] GetEmpresas_x_Url(string url, ref string MensajeErrorOut) {
            Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest inValue = new Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest();
            inValue.url = url;
            inValue.MensajeErrorOut = MensajeErrorOut;
            Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlResponse retVal = ((Efirm.WSEfirm_Empresa.IWs_Empresa)(this)).GetEmpresas_x_Url(inValue);
            MensajeErrorOut = retVal.MensajeErrorOut;
            return retVal.GetEmpresas_x_UrlResult;
        }
        
        public System.Threading.Tasks.Task<Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlResponse> GetEmpresas_x_UrlAsync(Efirm.WSEfirm_Empresa.GetEmpresas_x_UrlRequest request) {
            return base.Channel.GetEmpresas_x_UrlAsync(request);
        }
    }
}
