//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class fa_elec_registros_generados
    {
        public string ID_REGISTRO { get; set; }
        public System.DateTime FECHA_CARGA { get; set; }
        public string ESTADO { get; set; }
    }
}
