//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_plantilla_correo_x_cuenta
    {
        public string IdCuenta { get; set; }
        public string Asunto { get; set; }
        public string cuerpo_correo { get; set; }
    }
}
