//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Horario_envio_recepcion
    {
        public string IdHorario_Envio_Recep { get; set; }
        public string Nombre { get; set; }
        public string Descripcion_a_mostrar { get; set; }
        public int Valor { get; set; }
        public bool Chequeado { get; set; }
        public string IdTipoTiempo { get; set; }
    }
}
