//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Catalogo_Tipo
    {
        public mail_Catalogo_Tipo()
        {
            this.mail_Catalogo = new HashSet<mail_Catalogo>();
        }
    
        public string IdTipoCatalogo { get; set; }
        public string nom_TipoCatalogo { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<mail_Catalogo> mail_Catalogo { get; set; }
    }
}
