//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Parametro
    {
        public string IdParametro { get; set; }
        public int valor_min_envi_recep_aut { get; set; }
        public bool envio_recep_aut_salir { get; set; }
        public Nullable<bool> enviar_solo_pdf_ride { get; set; }
        public Nullable<bool> enviar_solo_xml_ride { get; set; }
    }
}
