//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mensaje_Archi_Adjunto
    {
        public decimal IdMensaje { get; set; }
        public int Secuencia { get; set; }
        public byte[] Archivo_adjunto { get; set; }
        public string descripcion_archi { get; set; }
        public string extencion { get; set; }
        public string IdComprobante { get; set; }
        public Nullable<int> IdEmpresa { get; set; }
    
        public virtual mail_Mensaje mail_Mensaje { get; set; }
    }
}
