//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Catalogo
    {
        public string IdCatalogo { get; set; }
        public string nom_catalogo { get; set; }
        public string IdTipoCatalogo { get; set; }
        public string estado { get; set; }
    
        public virtual mail_Catalogo_Tipo mail_Catalogo_Tipo { get; set; }
    }
}
