//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Cuentas_Correo_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public string IdCuenta { get; set; }
        public string observacion { get; set; }
    
        public virtual mail_Cuentas_Correo mail_Cuentas_Correo { get; set; }
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
