//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mensaje_Tipo
    {
        public mail_Mensaje_Tipo()
        {
            this.mail_Mensaje = new HashSet<mail_Mensaje>();
        }
    
        public string IdTipo_Mensaje { get; set; }
        public string descripcion { get; set; }
        public Nullable<int> orden { get; set; }
        public string estado { get; set; }
    
        public virtual ICollection<mail_Mensaje> mail_Mensaje { get; set; }
    }
}
