//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects; 
    //using System.Data.Objects;
    //using System.Data.Objects.DataClasses;
    //using System.Linq;
    
    public partial class EntitiesFactElectronica : DbContext
    {
        public EntitiesFactElectronica()
            : base("name=EntitiesFactElectronica")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mail_Catalogo> mail_Catalogo { get; set; }
        public DbSet<mail_Catalogo_Tipo> mail_Catalogo_Tipo { get; set; }
        public DbSet<mail_Cuentas_Correo> mail_Cuentas_Correo { get; set; }
        public DbSet<mail_Cuentas_Correo_x_Empresa> mail_Cuentas_Correo_x_Empresa { get; set; }
        public DbSet<mail_Mensaje> mail_Mensaje { get; set; }
        public DbSet<mail_Mensaje_Archi_Adjunto> mail_Mensaje_Archi_Adjunto { get; set; }
        public DbSet<mail_Mensaje_Tipo> mail_Mensaje_Tipo { get; set; }
        public DbSet<mail_Parametro> mail_Parametro { get; set; }
        public DbSet<mail_plantilla_correo_x_cuenta> mail_plantilla_correo_x_cuenta { get; set; }
        public DbSet<tb_Actividades_Horario> tb_Actividades_Horario { get; set; }
        public DbSet<tb_Actividades_Horario_Acciones> tb_Actividades_Horario_Acciones { get; set; }
        public DbSet<tb_Actividades_Horario_Tipo_Ejecucion> tb_Actividades_Horario_Tipo_Ejecucion { get; set; }
        public DbSet<tb_Actividades_Horario_Tipo_Tiempo> tb_Actividades_Horario_Tipo_Tiempo { get; set; }
        public DbSet<tb_Catalogo> tb_Catalogo { get; set; }
        public DbSet<tb_Catalogo_tipo> tb_Catalogo_tipo { get; set; }
        public DbSet<tb_Clave_Conting> tb_Clave_Conting { get; set; }
        public DbSet<tb_Comprobante_estado_proceso> tb_Comprobante_estado_proceso { get; set; }
        public DbSet<tb_comprobante_exportado_base_ext> tb_comprobante_exportado_base_ext { get; set; }
        public DbSet<tb_Comprobante_Hist_Eliminado> tb_Comprobante_Hist_Eliminado { get; set; }
        public DbSet<tb_Comprobante_tipo> tb_Comprobante_tipo { get; set; }
        public DbSet<tb_Comprobante_tipo_estado> tb_Comprobante_tipo_estado { get; set; }
        public DbSet<tb_Comprobante_tipo_x_empresa> tb_Comprobante_tipo_x_empresa { get; set; }
        public DbSet<tb_comprobantes_No_Generados> tb_comprobantes_No_Generados { get; set; }
        public DbSet<tb_Contribuyente> tb_Contribuyente { get; set; }
        public DbSet<tb_directorio> tb_directorio { get; set; }
        public DbSet<tb_Empresa_externa> tb_Empresa_externa { get; set; }
        public DbSet<tb_Error_sri> tb_Error_sri { get; set; }
        public DbSet<tb_sis_Log_Error_Vzen> tb_sis_Log_Error_Vzen { get; set; }
        public DbSet<tb_Sucursal> tb_Sucursal { get; set; }
        public DbSet<tb_Tocken> tb_Tocken { get; set; }
        public DbSet<tb_Tocken_x_Usuario_Tocken> tb_Tocken_x_Usuario_Tocken { get; set; }
        public DbSet<tb_Usuario> tb_Usuario { get; set; }
        public DbSet<tb_Usuario_Tocken> tb_Usuario_Tocken { get; set; }
        public DbSet<vw_Comprobante_Autorizados_Enviados_NoEnviados_mail> vw_Comprobante_Autorizados_Enviados_NoEnviados_mail { get; set; }
        public DbSet<vw_comprobante_pendiente_de_Autorizacion_sri> vw_comprobante_pendiente_de_Autorizacion_sri { get; set; }
        public DbSet<vw_Comprobante_Tipo> vw_Comprobante_Tipo { get; set; }
        public DbSet<vw_Comprobantes_recibidos> vw_Comprobantes_recibidos { get; set; }
        public DbSet<vw_mail_Cuentas_Correo_x_mail_Mensaje_Tipo> vw_mail_Cuentas_Correo_x_mail_Mensaje_Tipo { get; set; }
        public DbSet<vw_Mensaje_x_Contribuyente> vw_Mensaje_x_Contribuyente { get; set; }
        public DbSet<vwSerWeb_Comprobante> vwSerWeb_Comprobante { get; set; }
        public DbSet<vwtb_Comprobante_para_exportar> vwtb_Comprobante_para_exportar { get; set; }
        public DbSet<wv_mail_Cuentas_Correo_x_Empresa> wv_mail_Cuentas_Correo_x_Empresa { get; set; }
        public DbSet<tb_FormaPago> tb_FormaPago { get; set; }
        public DbSet<vw_Comprobante> vw_Comprobante { get; set; }
        public DbSet<vwseg_menu_x_tb_empresa_x_seg_usuario> vwseg_menu_x_tb_empresa_x_seg_usuario { get; set; }
        public DbSet<seg_menu> seg_menu { get; set; }
        public DbSet<seg_menu_x_tb_empresa> seg_menu_x_tb_empresa { get; set; }
        public DbSet<seg_menu_x_tb_empresa_x_seg_usuario> seg_menu_x_tb_empresa_x_seg_usuario { get; set; }
        public DbSet<vwseg_usuario_x_tb_empresa> vwseg_usuario_x_tb_empresa { get; set; }
        public DbSet<seg_usuario> seg_usuario { get; set; }
        public DbSet<seg_usuario_x_tb_empresa> seg_usuario_x_tb_empresa { get; set; }
        public DbSet<tb_Empresa> tb_Empresa { get; set; }
        public DbSet<tb_Comprobante> tb_Comprobante { get; set; }
        public DbSet<tb_Parametro> tb_Parametro { get; set; }
        public DbSet<tb_comprobante_x_valor> tb_comprobante_x_valor { get; set; }
        public DbSet<tb_facturas_eventos> tb_facturas_eventos { get; set; }
    
        public virtual int sp_RecuperaciondeContraseña(Nullable<int> idEmpresa, string cedulaRuc)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var cedulaRucParameter = cedulaRuc != null ?
                new ObjectParameter("cedulaRuc", cedulaRuc) :
                new ObjectParameter("cedulaRuc", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_RecuperaciondeContraseña", idEmpresaParameter, cedulaRucParameter);
        }
    
        public virtual int sp_Registro_Contribuyente(Nullable<int> idEmpresa, string cedulaRuc, string idTipoComprobante, string numComprobante, string correo, string contrasenia, string hashText)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var cedulaRucParameter = cedulaRuc != null ?
                new ObjectParameter("CedulaRuc", cedulaRuc) :
                new ObjectParameter("CedulaRuc", typeof(string));
    
            var idTipoComprobanteParameter = idTipoComprobante != null ?
                new ObjectParameter("IdTipoComprobante", idTipoComprobante) :
                new ObjectParameter("IdTipoComprobante", typeof(string));
    
            var numComprobanteParameter = numComprobante != null ?
                new ObjectParameter("NumComprobante", numComprobante) :
                new ObjectParameter("NumComprobante", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("Correo", correo) :
                new ObjectParameter("Correo", typeof(string));
    
            var contraseniaParameter = contrasenia != null ?
                new ObjectParameter("Contrasenia", contrasenia) :
                new ObjectParameter("Contrasenia", typeof(string));
    
            var hashTextParameter = hashText != null ?
                new ObjectParameter("HashText", hashText) :
                new ObjectParameter("HashText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_Registro_Contribuyente", idEmpresaParameter, cedulaRucParameter, idTipoComprobanteParameter, numComprobanteParameter, correoParameter, contraseniaParameter, hashTextParameter);
        }
    
        public virtual int sp_ValidarRegistros(Nullable<int> idEmpresa, string hashText)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var hashTextParameter = hashText != null ?
                new ObjectParameter("HashText", hashText) :
                new ObjectParameter("HashText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ValidarRegistros", idEmpresaParameter, hashTextParameter);
        }
    
        public virtual ObjectResult<sp_consulta_x_Cbte_Recibidos_x_Pagina_Result> sp_consulta_x_Cbte_Recibidos_x_Pagina(Nullable<int> pagina, Nullable<int> registrosporPagina, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string cadenaBusqueda)
        {
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var registrosporPaginaParameter = registrosporPagina.HasValue ?
                new ObjectParameter("RegistrosporPagina", registrosporPagina) :
                new ObjectParameter("RegistrosporPagina", typeof(int));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var cadenaBusquedaParameter = cadenaBusqueda != null ?
                new ObjectParameter("CadenaBusqueda", cadenaBusqueda) :
                new ObjectParameter("CadenaBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_x_Cbte_Recibidos_x_Pagina_Result>("sp_consulta_x_Cbte_Recibidos_x_Pagina", paginaParameter, registrosporPaginaParameter, fechaIniParameter, fechaFinParameter, cadenaBusquedaParameter);
        }
    
        public virtual ObjectResult<sp_consulta_x_cbtes_x_paginas_Result> sp_consulta_x_cbtes_x_paginas(Nullable<int> idEmpresa, Nullable<int> tamanio_Pagina, Nullable<int> indice_Pagina, string cedulaRuc, string tipoComprobante, string string_a_buscar, Nullable<System.DateTime> fecIni, Nullable<System.DateTime> fecFin)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var tamanio_PaginaParameter = tamanio_Pagina.HasValue ?
                new ObjectParameter("Tamanio_Pagina", tamanio_Pagina) :
                new ObjectParameter("Tamanio_Pagina", typeof(int));
    
            var indice_PaginaParameter = indice_Pagina.HasValue ?
                new ObjectParameter("Indice_Pagina", indice_Pagina) :
                new ObjectParameter("Indice_Pagina", typeof(int));
    
            var cedulaRucParameter = cedulaRuc != null ?
                new ObjectParameter("CedulaRuc", cedulaRuc) :
                new ObjectParameter("CedulaRuc", typeof(string));
    
            var tipoComprobanteParameter = tipoComprobante != null ?
                new ObjectParameter("TipoComprobante", tipoComprobante) :
                new ObjectParameter("TipoComprobante", typeof(string));
    
            var string_a_buscarParameter = string_a_buscar != null ?
                new ObjectParameter("String_a_buscar", string_a_buscar) :
                new ObjectParameter("String_a_buscar", typeof(string));
    
            var fecIniParameter = fecIni.HasValue ?
                new ObjectParameter("FecIni", fecIni) :
                new ObjectParameter("FecIni", typeof(System.DateTime));
    
            var fecFinParameter = fecFin.HasValue ?
                new ObjectParameter("FecFin", fecFin) :
                new ObjectParameter("FecFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_x_cbtes_x_paginas_Result>("sp_consulta_x_cbtes_x_paginas", idEmpresaParameter, tamanio_PaginaParameter, indice_PaginaParameter, cedulaRucParameter, tipoComprobanteParameter, string_a_buscarParameter, fecIniParameter, fecFinParameter);
        }
    
        public virtual ObjectResult<sp_VerificarRecuperaciondeContrasenia_Result> sp_VerificarRecuperaciondeContrasenia(Nullable<int> idEmpresa, string hashText)
        {
            var idEmpresaParameter = idEmpresa.HasValue ?
                new ObjectParameter("IdEmpresa", idEmpresa) :
                new ObjectParameter("IdEmpresa", typeof(int));
    
            var hashTextParameter = hashText != null ?
                new ObjectParameter("HashText", hashText) :
                new ObjectParameter("HashText", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_VerificarRecuperaciondeContrasenia_Result>("sp_VerificarRecuperaciondeContrasenia", idEmpresaParameter, hashTextParameter);
        }
    
        public virtual ObjectResult<sp_consulta_x_CbteVALI_FIRM_REC_x_Pagina_Result> sp_consulta_x_CbteVALI_FIRM_REC_x_Pagina(Nullable<int> idEmpresaIni, Nullable<int> idEmpresaFin, string idTipoCbteIni, string idTipoCbteFin, Nullable<int> pagina, Nullable<int> registrosporPagina, Nullable<System.DateTime> fechaIni, Nullable<System.DateTime> fechaFin, string idEstado_cbte, string estadoDoc, string idEstadoProceso, string cadenaBusqueda)
        {
            var idEmpresaIniParameter = idEmpresaIni.HasValue ?
                new ObjectParameter("IdEmpresaIni", idEmpresaIni) :
                new ObjectParameter("IdEmpresaIni", typeof(int));
    
            var idEmpresaFinParameter = idEmpresaFin.HasValue ?
                new ObjectParameter("IdEmpresaFin", idEmpresaFin) :
                new ObjectParameter("IdEmpresaFin", typeof(int));
    
            var idTipoCbteIniParameter = idTipoCbteIni != null ?
                new ObjectParameter("IdTipoCbteIni", idTipoCbteIni) :
                new ObjectParameter("IdTipoCbteIni", typeof(string));
    
            var idTipoCbteFinParameter = idTipoCbteFin != null ?
                new ObjectParameter("IdTipoCbteFin", idTipoCbteFin) :
                new ObjectParameter("IdTipoCbteFin", typeof(string));
    
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var registrosporPaginaParameter = registrosporPagina.HasValue ?
                new ObjectParameter("RegistrosporPagina", registrosporPagina) :
                new ObjectParameter("RegistrosporPagina", typeof(int));
    
            var fechaIniParameter = fechaIni.HasValue ?
                new ObjectParameter("FechaIni", fechaIni) :
                new ObjectParameter("FechaIni", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("FechaFin", fechaFin) :
                new ObjectParameter("FechaFin", typeof(System.DateTime));
    
            var idEstado_cbteParameter = idEstado_cbte != null ?
                new ObjectParameter("IdEstado_cbte", idEstado_cbte) :
                new ObjectParameter("IdEstado_cbte", typeof(string));
    
            var estadoDocParameter = estadoDoc != null ?
                new ObjectParameter("EstadoDoc", estadoDoc) :
                new ObjectParameter("EstadoDoc", typeof(string));
    
            var idEstadoProcesoParameter = idEstadoProceso != null ?
                new ObjectParameter("IdEstadoProceso", idEstadoProceso) :
                new ObjectParameter("IdEstadoProceso", typeof(string));
    
            var cadenaBusquedaParameter = cadenaBusqueda != null ?
                new ObjectParameter("CadenaBusqueda", cadenaBusqueda) :
                new ObjectParameter("CadenaBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_x_CbteVALI_FIRM_REC_x_Pagina_Result>("sp_consulta_x_CbteVALI_FIRM_REC_x_Pagina", idEmpresaIniParameter, idEmpresaFinParameter, idTipoCbteIniParameter, idTipoCbteFinParameter, paginaParameter, registrosporPaginaParameter, fechaIniParameter, fechaFinParameter, idEstado_cbteParameter, estadoDocParameter, idEstadoProcesoParameter, cadenaBusquedaParameter);
        }
    
        public virtual ObjectResult<sp_consulta_x_Mensaje_x_Pagina_Result> sp_consulta_x_Mensaje_x_Pagina(Nullable<int> pagina, Nullable<int> registrosporPagina, string tipoCorreo, string direccionCorreo, string cadenaBusqueda)
        {
            var paginaParameter = pagina.HasValue ?
                new ObjectParameter("Pagina", pagina) :
                new ObjectParameter("Pagina", typeof(int));
    
            var registrosporPaginaParameter = registrosporPagina.HasValue ?
                new ObjectParameter("RegistrosporPagina", registrosporPagina) :
                new ObjectParameter("RegistrosporPagina", typeof(int));
    
            var tipoCorreoParameter = tipoCorreo != null ?
                new ObjectParameter("TipoCorreo", tipoCorreo) :
                new ObjectParameter("TipoCorreo", typeof(string));
    
            var direccionCorreoParameter = direccionCorreo != null ?
                new ObjectParameter("direccionCorreo", direccionCorreo) :
                new ObjectParameter("direccionCorreo", typeof(string));
    
            var cadenaBusquedaParameter = cadenaBusqueda != null ?
                new ObjectParameter("CadenaBusqueda", cadenaBusqueda) :
                new ObjectParameter("CadenaBusqueda", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_x_Mensaje_x_Pagina_Result>("sp_consulta_x_Mensaje_x_Pagina", paginaParameter, registrosporPaginaParameter, tipoCorreoParameter, direccionCorreoParameter, cadenaBusquedaParameter);
        }
    }
}
