//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Actividades_Horario_Acciones
    {
        public string IdTransaccion { get; set; }
        public string IdAccion { get; set; }
        public string Descripcion { get; set; }
        public int TiempoEspera { get; set; }
        public int Secuencia_ejecucion { get; set; }
    
        public virtual tb_Actividades_Horario tb_Actividades_Horario { get; set; }
    }
}
