//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Actividades_Horario_Tipo_Tiempo
    {
        public tb_Actividades_Horario_Tipo_Tiempo()
        {
            this.tb_Actividades_Horario = new HashSet<tb_Actividades_Horario>();
        }
    
        public string IdTipoTiempo { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<tb_Actividades_Horario> tb_Actividades_Horario { get; set; }
    }
}
