//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_comprobantes_No_Generados
    {
        public string id_Comprobante { get; set; }
        public string Nom_vista { get; set; }
        public string Mensaje_Error { get; set; }
        public System.DateTime Fecha_Carga { get; set; }
    }
}
