//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comprobante_tipo_estado
    {
        public tb_Comprobante_tipo_estado()
        {
            this.tb_Comprobante = new HashSet<tb_Comprobante>();
        }
    
        public string IdEstado_cbte { get; set; }
        public string descripcion_estado { get; set; }
    
        public virtual ICollection<tb_Comprobante> tb_Comprobante { get; set; }
    }
}
