//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comprobante_tipo_x_empresa
    {
        public int IdEmpresa { get; set; }
        public string IdComprobante_tipo { get; set; }
        public byte[] File_disenio_rpt { get; set; }
    }
}
