//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_facturas_eventos
    {
        public int IdEmpresa { get; set; }
        public string Establecimiento { get; set; }
        public string Puntoemision { get; set; }
        public decimal NumFactura { get; set; }
        public Nullable<decimal> Cantidad { get; set; }
        public Nullable<decimal> ValorUnitario { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
        public Nullable<decimal> Iva { get; set; }
        public Nullable<decimal> Total { get; set; }
        public int Evento { get; set; }
        public int Factura { get; set; }
        public string Nombre_Evento { get; set; }
        public string Observacion { get; set; }
    }
}
