//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Log_Error_Vzen
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> Fecha_Trans { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public string Clase { get; set; }
        public string Pantalla { get; set; }
        public string Asamble { get; set; }
        public string Usuario { get; set; }
        public string Ip { get; set; }
        public string PC { get; set; }
    }
}
