//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Sucursal
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public string DirEstablecimiento { get; set; }
        public string Establecimiento { get; set; }
        public string PtoEmision { get; set; }
        public string Secuencial { get; set; }
        public bool Estado { get; set; }
    
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
