//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Tocken
    {
        public string IdTocken { get; set; }
        public string nom_tocken { get; set; }
        public string Password { get; set; }
        public string Serie { get; set; }
        public string Modelo { get; set; }
        public string IdTipo { get; set; }
        public string Estado { get; set; }
    }
}
