//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Usuario
    {
        public int IdUsuario { get; set; }
        public string Usuario { get; set; }
        public string Contrasenia { get; set; }
        public bool Estado { get; set; }
    }
}
