//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_Comprobantes_recibidos
    {
        public string descripcion_archi { get; set; }
        public string extencion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Asunto { get; set; }
        public string mail_emisor { get; set; }
        public string Ced_Ruc_Emisor { get; set; }
        public string Razon_Social_emisor { get; set; }
        public string sXml { get; set; }
        public string IdTipo_Mensaje { get; set; }
        public string codMensajeId { get; set; }
        public string IdCuenta { get; set; }
        public string Texto_mensaje { get; set; }
        public int Secuencia { get; set; }
        public byte[] Archivo_adjunto { get; set; }
        public string Para { get; set; }
        public decimal IdMensaje { get; set; }
        public string Ambiente { get; set; }
        public string TipoDocumento { get; set; }
    }
}
