//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwfe_factura
    {
        public int IdEmpresa { get; set; }
        public int IdSucursal { get; set; }
        public int IdBodega { get; set; }
        public decimal IdCbteVta { get; set; }
        public string vt_serie1 { get; set; }
        public string vt_serie2 { get; set; }
        public string vt_NumFactura { get; set; }
        public System.DateTime vt_fecha { get; set; }
        public string pe_Naturaleza { get; set; }
        public string IdTipoDocumento { get; set; }
        public string pe_cedulaRuc { get; set; }
        public string Nombres { get; set; }
        public string Telefono { get; set; }
        public string Celular { get; set; }
        public string Correo { get; set; }
        public string Direccion { get; set; }
        public string RazonSocial { get; set; }
        public string NombreComercial { get; set; }
        public string ContribuyenteEspecial { get; set; }
        public string ObligadoAllevarConta { get; set; }
        public string em_ruc { get; set; }
        public string em_direccion { get; set; }
        public string nom_FormaPago { get; set; }
        public string IdFormaPago { get; set; }
        public int Dias_Vct { get; set; }
        public Nullable<decimal> Base_imponible { get; set; }
        public Nullable<decimal> impuesto { get; set; }
        public Nullable<decimal> totalDescuento { get; set; }
        public Nullable<decimal> total_sin_impuesto { get; set; }
        public Nullable<decimal> importeTotal { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string em_telefonos { get; set; }
    }
}
