//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwseg_menu_x_tb_empresa_x_seg_usuario
    {
        public int IdEmpresa { get; set; }
        public int IdMenu { get; set; }
        public string IdUsuario { get; set; }
        public bool nuevo { get; set; }
        public bool modificar { get; set; }
        public bool consultar { get; set; }
        public bool anular { get; set; }
    }
}
