//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwseg_usuario_x_tb_empresa
    {
        public int IdEmpresa { get; set; }
        public string IdUsuario { get; set; }
        public string RazonSocial { get; set; }
        public string us_contrasenia { get; set; }
        public string us_nombre { get; set; }
    }
}
