//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class wv_mail_Cuentas_Correo_x_Empresa
    {
        public int IdEmpresa { get; set; }
        public string IdCuenta { get; set; }
        public string observacion { get; set; }
        public string RazonSocial { get; set; }
        public string Nombre_cuenta { get; set; }
        public string direccion_correo { get; set; }
    }
}
