//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailEfirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class mail_Mensaje_Tipo
    {
        public mail_Mensaje_Tipo()
        {
            this.mail_Mensaje = new HashSet<mail_Mensaje>();
        }
    
        public string IdTipo_Mensaje { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<mail_Mensaje> mail_Mensaje { get; set; }
    }
}
