//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailEfirm.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities_Mail_Efirm : DbContext
    {
        public Entities_Mail_Efirm()
            : base("name=Entities_Mail_Efirm")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<mail_Mensaje_Archi_Adjunto> mail_Mensaje_Archi_Adjunto { get; set; }
        public DbSet<mail_Mensaje_Tipo> mail_Mensaje_Tipo { get; set; }
        public DbSet<mail_Mensaje> mail_Mensaje { get; set; }
        public DbSet<tb_Contribuyente> tb_Contribuyente { get; set; }
        public DbSet<tb_Empresa> tb_Empresa { get; set; }
    }
}
