//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MailEfirm.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Contribuyente
    {
        public tb_Contribuyente()
        {
            this.mail_Mensaje = new HashSet<mail_Mensaje>();
        }
    
        public decimal IdContribuyente { get; set; }
        public int IdEmpresa { get; set; }
        public string cedulaRuc_contri { get; set; }
        public string Nom_Contribuyente { get; set; }
        public string Mail { get; set; }
        public string Mail_secundario { get; set; }
        public bool EsCliente { get; set; }
        public bool EsProveedor { get; set; }
        public string Password { get; set; }
        public bool Estado { get; set; }
        public Nullable<System.DateTime> Fecha_transaccion { get; set; }
        public Nullable<System.DateTime> Fecha_Registro_web { get; set; }
        public Nullable<System.DateTime> Fecha_Actualizacion_datos { get; set; }
        public bool Registrado_web { get; set; }
        public string Observacion { get; set; }
        public string TipoContacto { get; set; }
        public byte[] Foto { get; set; }
        public string Direccion { get; set; }
        public string Telefono { get; set; }
    
        public virtual ICollection<mail_Mensaje> mail_Mensaje { get; set; }
    }
}
