//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Comprobante
    {
        public int IdEmpresa { get; set; }
        public string IdComprobante { get; set; }
        public string IdTipoDocumento { get; set; }
        public string IdEstado_cbte { get; set; }
        public int secuencial { get; set; }
        public string Cedula_Ruc { get; set; }
        public string Numero_Autorizacion { get; set; }
        public string s_XML { get; set; }
        public string s_XML_Firmado { get; set; }
        public string XML_file { get; set; }
        public Nullable<System.DateTime> Fecha_Emi_Fact { get; set; }
        public Nullable<System.DateTime> Fecha_transaccion { get; set; }
        public Nullable<System.DateTime> FechaAutorizacion { get; set; }
        public string IdEstadoDeEnvio { get; set; }
        public string ClaveContingencia { get; set; }
        public string RutaArchivo { get; set; }
        public string EstadoDoc { get; set; }
        public string Error { get; set; }
        public bool Estado { get; set; }
        public string IdError_Sri { get; set; }
    
        public virtual tb_Empresa tb_Empresa { get; set; }
    }
}
