//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Data.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_sis_Log_Error_Vzen
    {
        public decimal Id { get; set; }
        public Nullable<System.DateTime> Fecha_Trans { get; set; }
        public string Detalle { get; set; }
        public string Tipo { get; set; }
        public string Clase { get; set; }
        public string Pantalla { get; set; }
        public string Asamble { get; set; }
        public string Usuario { get; set; }
        public string Ip { get; set; }
        public string PC { get; set; }
    }
}
