//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FirmElect.Bus.Java {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WS.firmaelectronica/", ConfigurationName="Java.EFirm")]
    public interface EFirm {
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/FirmarRequest", ReplyAction="http://WS.firmaelectronica/EFirm/FirmarResponse")]
        FirmElect.Bus.Java.FirmarResponse Firmar(FirmElect.Bus.Java.FirmarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/FirmarRequest", ReplyAction="http://WS.firmaelectronica/EFirm/FirmarResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.FirmarResponse> FirmarAsync(FirmElect.Bus.Java.FirmarRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetTokensRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetTokensResponse")]
        FirmElect.Bus.Java.GetTokensResponse GetTokens(FirmElect.Bus.Java.GetTokensRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetTokensRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetTokensResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTokensResponse> GetTokensAsync(FirmElect.Bus.Java.GetTokensRequest request);
        
        // CODEGEN: Generating message contract since element name arg1 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/LoginRequest", ReplyAction="http://WS.firmaelectronica/EFirm/LoginResponse")]
        FirmElect.Bus.Java.LoginResponse Login(FirmElect.Bus.Java.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/LoginRequest", ReplyAction="http://WS.firmaelectronica/EFirm/LoginResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.LoginResponse> LoginAsync(FirmElect.Bus.Java.LoginRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetDatosUsuarioRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetDatosUsuarioResponse")]
        FirmElect.Bus.Java.GetDatosUsuarioResponse GetDatosUsuario(FirmElect.Bus.Java.GetDatosUsuarioRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetDatosUsuarioRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetDatosUsuarioResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetDatosUsuarioResponse> GetDatosUsuarioAsync(FirmElect.Bus.Java.GetDatosUsuarioRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyUserRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyUserResponse")]
        FirmElect.Bus.Java.SetParametroProxyUserResponse SetParametroProxyUser(FirmElect.Bus.Java.SetParametroProxyUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyUserRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyUserResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUserResponse> SetParametroProxyUserAsync(FirmElect.Bus.Java.SetParametroProxyUserRequest request);
        
        // CODEGEN: Generating message contract since element name return from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetTiposAutentificacionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetTiposAutentificacionResponse")]
        FirmElect.Bus.Java.GetTiposAutentificacionResponse GetTiposAutentificacion(FirmElect.Bus.Java.GetTiposAutentificacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetTiposAutentificacionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetTiposAutentificacionResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTiposAutentificacionResponse> GetTiposAutentificacionAsync(FirmElect.Bus.Java.GetTiposAutentificacionRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetAutorizacionWSRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetAutorizacionWSResponse")]
        FirmElect.Bus.Java.GetAutorizacionWSResponse GetAutorizacionWS(FirmElect.Bus.Java.GetAutorizacionWSRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/GetAutorizacionWSRequest", ReplyAction="http://WS.firmaelectronica/EFirm/GetAutorizacionWSResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetAutorizacionWSResponse> GetAutorizacionWSAsync(FirmElect.Bus.Java.GetAutorizacionWSRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyPortRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyPortResponse")]
        FirmElect.Bus.Java.SetParametroProxyPortResponse SetParametroProxyPort(FirmElect.Bus.Java.SetParametroProxyPortRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyPortRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyPortResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPortResponse> SetParametroProxyPortAsync(FirmElect.Bus.Java.SetParametroProxyPortRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroUrlWSRecepcionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroUrlWSRecepcionResponse")]
        FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse SetParametroUrlWSRecepcion(FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroUrlWSRecepcionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroUrlWSRecepcionResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse> SetParametroUrlWSRecepcionAsync(FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroAmbienteRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroAmbienteResponse")]
        FirmElect.Bus.Java.SetParametroAmbienteResponse SetParametroAmbiente(FirmElect.Bus.Java.SetParametroAmbienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroAmbienteRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroAmbienteResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroAmbienteResponse> SetParametroAmbienteAsync(FirmElect.Bus.Java.SetParametroAmbienteRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyPassRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyPassResponse")]
        FirmElect.Bus.Java.SetParametroProxyPassResponse SetParametroProxyPass(FirmElect.Bus.Java.SetParametroProxyPassRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyPassRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyPassResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPassResponse> SetParametroProxyPassAsync(FirmElect.Bus.Java.SetParametroProxyPassRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyUrlRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyUrlResponse")]
        FirmElect.Bus.Java.SetParametroProxyUrlResponse SetParametroProxyUrl(FirmElect.Bus.Java.SetParametroProxyUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroProxyUrlRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroProxyUrlResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUrlResponse> SetParametroProxyUrlAsync(FirmElect.Bus.Java.SetParametroProxyUrlRequest request);
        
        // CODEGEN: Generating message contract since element name arg0 from namespace  is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroUrlWSAutorizacionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroUrlWSAutorizacionResponse")]
        FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse SetParametroUrlWSAutorizacion(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WS.firmaelectronica/EFirm/SetParametroUrlWSAutorizacionRequest", ReplyAction="http://WS.firmaelectronica/EFirm/SetParametroUrlWSAutorizacionResponse")]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse> SetParametroUrlWSAutorizacionAsync(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirmarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Firmar", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.FirmarRequestBody Body;
        
        public FirmarRequest() {
        }
        
        public FirmarRequest(FirmElect.Bus.Java.FirmarRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class FirmarRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public FirmarRequestBody() {
        }
        
        public FirmarRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FirmarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FirmarResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.FirmarResponseBody Body;
        
        public FirmarResponse() {
        }
        
        public FirmarResponse(FirmElect.Bus.Java.FirmarResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class FirmarResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public FirmarResponseBody() {
        }
        
        public FirmarResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokensRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokens", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetTokensRequestBody Body;
        
        public GetTokensRequest() {
        }
        
        public GetTokensRequest(FirmElect.Bus.Java.GetTokensRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTokensRequestBody {
        
        public GetTokensRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTokensResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTokensResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetTokensResponseBody Body;
        
        public GetTokensResponse() {
        }
        
        public GetTokensResponse(FirmElect.Bus.Java.GetTokensResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetTokensResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetTokensResponseBody() {
        }
        
        public GetTokensResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(FirmElect.Bus.Java.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int arg0;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string arg1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string arg2;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(int arg0, string arg1, string arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(FirmElect.Bus.Java.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatosUsuarioRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatosUsuario", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetDatosUsuarioRequestBody Body;
        
        public GetDatosUsuarioRequest() {
        }
        
        public GetDatosUsuarioRequest(FirmElect.Bus.Java.GetDatosUsuarioRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetDatosUsuarioRequestBody {
        
        public GetDatosUsuarioRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDatosUsuarioResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDatosUsuarioResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetDatosUsuarioResponseBody Body;
        
        public GetDatosUsuarioResponse() {
        }
        
        public GetDatosUsuarioResponse(FirmElect.Bus.Java.GetDatosUsuarioResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetDatosUsuarioResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetDatosUsuarioResponseBody() {
        }
        
        public GetDatosUsuarioResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyUser", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyUserRequestBody Body;
        
        public SetParametroProxyUserRequest() {
        }
        
        public SetParametroProxyUserRequest(FirmElect.Bus.Java.SetParametroProxyUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroProxyUserRequestBody() {
        }
        
        public SetParametroProxyUserRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyUserResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyUserResponseBody Body;
        
        public SetParametroProxyUserResponse() {
        }
        
        public SetParametroProxyUserResponse(FirmElect.Bus.Java.SetParametroProxyUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroProxyUserResponseBody() {
        }
        
        public SetParametroProxyUserResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiposAutentificacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiposAutentificacion", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetTiposAutentificacionRequestBody Body;
        
        public GetTiposAutentificacionRequest() {
        }
        
        public GetTiposAutentificacionRequest(FirmElect.Bus.Java.GetTiposAutentificacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTiposAutentificacionRequestBody {
        
        public GetTiposAutentificacionRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTiposAutentificacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTiposAutentificacionResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetTiposAutentificacionResponseBody Body;
        
        public GetTiposAutentificacionResponse() {
        }
        
        public GetTiposAutentificacionResponse(FirmElect.Bus.Java.GetTiposAutentificacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetTiposAutentificacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetTiposAutentificacionResponseBody() {
        }
        
        public GetTiposAutentificacionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAutorizacionWSRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAutorizacionWS", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetAutorizacionWSRequestBody Body;
        
        public GetAutorizacionWSRequest() {
        }
        
        public GetAutorizacionWSRequest(FirmElect.Bus.Java.GetAutorizacionWSRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAutorizacionWSRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public GetAutorizacionWSRequestBody() {
        }
        
        public GetAutorizacionWSRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAutorizacionWSResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAutorizacionWSResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.GetAutorizacionWSResponseBody Body;
        
        public GetAutorizacionWSResponse() {
        }
        
        public GetAutorizacionWSResponse(FirmElect.Bus.Java.GetAutorizacionWSResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class GetAutorizacionWSResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public GetAutorizacionWSResponseBody() {
        }
        
        public GetAutorizacionWSResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyPortRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyPort", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyPortRequestBody Body;
        
        public SetParametroProxyPortRequest() {
        }
        
        public SetParametroProxyPortRequest(FirmElect.Bus.Java.SetParametroProxyPortRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyPortRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroProxyPortRequestBody() {
        }
        
        public SetParametroProxyPortRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyPortResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyPortResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyPortResponseBody Body;
        
        public SetParametroProxyPortResponse() {
        }
        
        public SetParametroProxyPortResponse(FirmElect.Bus.Java.SetParametroProxyPortResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyPortResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroProxyPortResponseBody() {
        }
        
        public SetParametroProxyPortResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroUrlWSRecepcionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroUrlWSRecepcion", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequestBody Body;
        
        public SetParametroUrlWSRecepcionRequest() {
        }
        
        public SetParametroUrlWSRecepcionRequest(FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroUrlWSRecepcionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroUrlWSRecepcionRequestBody() {
        }
        
        public SetParametroUrlWSRecepcionRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroUrlWSRecepcionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroUrlWSRecepcionResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponseBody Body;
        
        public SetParametroUrlWSRecepcionResponse() {
        }
        
        public SetParametroUrlWSRecepcionResponse(FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroUrlWSRecepcionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroUrlWSRecepcionResponseBody() {
        }
        
        public SetParametroUrlWSRecepcionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroAmbienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroAmbiente", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroAmbienteRequestBody Body;
        
        public SetParametroAmbienteRequest() {
        }
        
        public SetParametroAmbienteRequest(FirmElect.Bus.Java.SetParametroAmbienteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroAmbienteRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroAmbienteRequestBody() {
        }
        
        public SetParametroAmbienteRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroAmbienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroAmbienteResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroAmbienteResponseBody Body;
        
        public SetParametroAmbienteResponse() {
        }
        
        public SetParametroAmbienteResponse(FirmElect.Bus.Java.SetParametroAmbienteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroAmbienteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroAmbienteResponseBody() {
        }
        
        public SetParametroAmbienteResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyPassRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyPass", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyPassRequestBody Body;
        
        public SetParametroProxyPassRequest() {
        }
        
        public SetParametroProxyPassRequest(FirmElect.Bus.Java.SetParametroProxyPassRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyPassRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroProxyPassRequestBody() {
        }
        
        public SetParametroProxyPassRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyPassResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyPassResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyPassResponseBody Body;
        
        public SetParametroProxyPassResponse() {
        }
        
        public SetParametroProxyPassResponse(FirmElect.Bus.Java.SetParametroProxyPassResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyPassResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroProxyPassResponseBody() {
        }
        
        public SetParametroProxyPassResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyUrlRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyUrl", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyUrlRequestBody Body;
        
        public SetParametroProxyUrlRequest() {
        }
        
        public SetParametroProxyUrlRequest(FirmElect.Bus.Java.SetParametroProxyUrlRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyUrlRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroProxyUrlRequestBody() {
        }
        
        public SetParametroProxyUrlRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroProxyUrlResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroProxyUrlResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroProxyUrlResponseBody Body;
        
        public SetParametroProxyUrlResponse() {
        }
        
        public SetParametroProxyUrlResponse(FirmElect.Bus.Java.SetParametroProxyUrlResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroProxyUrlResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroProxyUrlResponseBody() {
        }
        
        public SetParametroProxyUrlResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroUrlWSAutorizacionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroUrlWSAutorizacion", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequestBody Body;
        
        public SetParametroUrlWSAutorizacionRequest() {
        }
        
        public SetParametroUrlWSAutorizacionRequest(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroUrlWSAutorizacionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string arg0;
        
        public SetParametroUrlWSAutorizacionRequestBody() {
        }
        
        public SetParametroUrlWSAutorizacionRequestBody(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SetParametroUrlWSAutorizacionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SetParametroUrlWSAutorizacionResponse", Namespace="http://WS.firmaelectronica/", Order=0)]
        public FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponseBody Body;
        
        public SetParametroUrlWSAutorizacionResponse() {
        }
        
        public SetParametroUrlWSAutorizacionResponse(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class SetParametroUrlWSAutorizacionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public SetParametroUrlWSAutorizacionResponseBody() {
        }
        
        public SetParametroUrlWSAutorizacionResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EFirmChannel : FirmElect.Bus.Java.EFirm, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EFirmClient : System.ServiceModel.ClientBase<FirmElect.Bus.Java.EFirm>, FirmElect.Bus.Java.EFirm {
        
        public EFirmClient() {
        }
        
        public EFirmClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EFirmClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EFirmClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EFirmClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.FirmarResponse FirmElect.Bus.Java.EFirm.Firmar(FirmElect.Bus.Java.FirmarRequest request) {
            return base.Channel.Firmar(request);
        }
        
        public string Firmar(string arg0) {
            FirmElect.Bus.Java.FirmarRequest inValue = new FirmElect.Bus.Java.FirmarRequest();
            inValue.Body = new FirmElect.Bus.Java.FirmarRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.FirmarResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).Firmar(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.FirmarResponse> FirmElect.Bus.Java.EFirm.FirmarAsync(FirmElect.Bus.Java.FirmarRequest request) {
            return base.Channel.FirmarAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.FirmarResponse> FirmarAsync(string arg0) {
            FirmElect.Bus.Java.FirmarRequest inValue = new FirmElect.Bus.Java.FirmarRequest();
            inValue.Body = new FirmElect.Bus.Java.FirmarRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).FirmarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.GetTokensResponse FirmElect.Bus.Java.EFirm.GetTokens(FirmElect.Bus.Java.GetTokensRequest request) {
            return base.Channel.GetTokens(request);
        }
        
        public string GetTokens() {
            FirmElect.Bus.Java.GetTokensRequest inValue = new FirmElect.Bus.Java.GetTokensRequest();
            inValue.Body = new FirmElect.Bus.Java.GetTokensRequestBody();
            FirmElect.Bus.Java.GetTokensResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).GetTokens(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTokensResponse> FirmElect.Bus.Java.EFirm.GetTokensAsync(FirmElect.Bus.Java.GetTokensRequest request) {
            return base.Channel.GetTokensAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTokensResponse> GetTokensAsync() {
            FirmElect.Bus.Java.GetTokensRequest inValue = new FirmElect.Bus.Java.GetTokensRequest();
            inValue.Body = new FirmElect.Bus.Java.GetTokensRequestBody();
            return ((FirmElect.Bus.Java.EFirm)(this)).GetTokensAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.LoginResponse FirmElect.Bus.Java.EFirm.Login(FirmElect.Bus.Java.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(int arg0, string arg1, string arg2) {
            FirmElect.Bus.Java.LoginRequest inValue = new FirmElect.Bus.Java.LoginRequest();
            inValue.Body = new FirmElect.Bus.Java.LoginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            FirmElect.Bus.Java.LoginResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).Login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.LoginResponse> FirmElect.Bus.Java.EFirm.LoginAsync(FirmElect.Bus.Java.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.LoginResponse> LoginAsync(int arg0, string arg1, string arg2) {
            FirmElect.Bus.Java.LoginRequest inValue = new FirmElect.Bus.Java.LoginRequest();
            inValue.Body = new FirmElect.Bus.Java.LoginRequestBody();
            inValue.Body.arg0 = arg0;
            inValue.Body.arg1 = arg1;
            inValue.Body.arg2 = arg2;
            return ((FirmElect.Bus.Java.EFirm)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.GetDatosUsuarioResponse FirmElect.Bus.Java.EFirm.GetDatosUsuario(FirmElect.Bus.Java.GetDatosUsuarioRequest request) {
            return base.Channel.GetDatosUsuario(request);
        }
        
        public string GetDatosUsuario() {
            FirmElect.Bus.Java.GetDatosUsuarioRequest inValue = new FirmElect.Bus.Java.GetDatosUsuarioRequest();
            inValue.Body = new FirmElect.Bus.Java.GetDatosUsuarioRequestBody();
            FirmElect.Bus.Java.GetDatosUsuarioResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).GetDatosUsuario(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetDatosUsuarioResponse> FirmElect.Bus.Java.EFirm.GetDatosUsuarioAsync(FirmElect.Bus.Java.GetDatosUsuarioRequest request) {
            return base.Channel.GetDatosUsuarioAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.GetDatosUsuarioResponse> GetDatosUsuarioAsync() {
            FirmElect.Bus.Java.GetDatosUsuarioRequest inValue = new FirmElect.Bus.Java.GetDatosUsuarioRequest();
            inValue.Body = new FirmElect.Bus.Java.GetDatosUsuarioRequestBody();
            return ((FirmElect.Bus.Java.EFirm)(this)).GetDatosUsuarioAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroProxyUserResponse FirmElect.Bus.Java.EFirm.SetParametroProxyUser(FirmElect.Bus.Java.SetParametroProxyUserRequest request) {
            return base.Channel.SetParametroProxyUser(request);
        }
        
        public string SetParametroProxyUser(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyUserRequest inValue = new FirmElect.Bus.Java.SetParametroProxyUserRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyUserRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroProxyUserResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyUser(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUserResponse> FirmElect.Bus.Java.EFirm.SetParametroProxyUserAsync(FirmElect.Bus.Java.SetParametroProxyUserRequest request) {
            return base.Channel.SetParametroProxyUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUserResponse> SetParametroProxyUserAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyUserRequest inValue = new FirmElect.Bus.Java.SetParametroProxyUserRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyUserRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.GetTiposAutentificacionResponse FirmElect.Bus.Java.EFirm.GetTiposAutentificacion(FirmElect.Bus.Java.GetTiposAutentificacionRequest request) {
            return base.Channel.GetTiposAutentificacion(request);
        }
        
        public string GetTiposAutentificacion() {
            FirmElect.Bus.Java.GetTiposAutentificacionRequest inValue = new FirmElect.Bus.Java.GetTiposAutentificacionRequest();
            inValue.Body = new FirmElect.Bus.Java.GetTiposAutentificacionRequestBody();
            FirmElect.Bus.Java.GetTiposAutentificacionResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).GetTiposAutentificacion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTiposAutentificacionResponse> FirmElect.Bus.Java.EFirm.GetTiposAutentificacionAsync(FirmElect.Bus.Java.GetTiposAutentificacionRequest request) {
            return base.Channel.GetTiposAutentificacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.GetTiposAutentificacionResponse> GetTiposAutentificacionAsync() {
            FirmElect.Bus.Java.GetTiposAutentificacionRequest inValue = new FirmElect.Bus.Java.GetTiposAutentificacionRequest();
            inValue.Body = new FirmElect.Bus.Java.GetTiposAutentificacionRequestBody();
            return ((FirmElect.Bus.Java.EFirm)(this)).GetTiposAutentificacionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.GetAutorizacionWSResponse FirmElect.Bus.Java.EFirm.GetAutorizacionWS(FirmElect.Bus.Java.GetAutorizacionWSRequest request) {
            return base.Channel.GetAutorizacionWS(request);
        }
        
        public string GetAutorizacionWS(string arg0) {
            FirmElect.Bus.Java.GetAutorizacionWSRequest inValue = new FirmElect.Bus.Java.GetAutorizacionWSRequest();
            inValue.Body = new FirmElect.Bus.Java.GetAutorizacionWSRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.GetAutorizacionWSResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).GetAutorizacionWS(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.GetAutorizacionWSResponse> FirmElect.Bus.Java.EFirm.GetAutorizacionWSAsync(FirmElect.Bus.Java.GetAutorizacionWSRequest request) {
            return base.Channel.GetAutorizacionWSAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.GetAutorizacionWSResponse> GetAutorizacionWSAsync(string arg0) {
            FirmElect.Bus.Java.GetAutorizacionWSRequest inValue = new FirmElect.Bus.Java.GetAutorizacionWSRequest();
            inValue.Body = new FirmElect.Bus.Java.GetAutorizacionWSRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).GetAutorizacionWSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroProxyPortResponse FirmElect.Bus.Java.EFirm.SetParametroProxyPort(FirmElect.Bus.Java.SetParametroProxyPortRequest request) {
            return base.Channel.SetParametroProxyPort(request);
        }
        
        public string SetParametroProxyPort(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyPortRequest inValue = new FirmElect.Bus.Java.SetParametroProxyPortRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyPortRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroProxyPortResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyPort(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPortResponse> FirmElect.Bus.Java.EFirm.SetParametroProxyPortAsync(FirmElect.Bus.Java.SetParametroProxyPortRequest request) {
            return base.Channel.SetParametroProxyPortAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPortResponse> SetParametroProxyPortAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyPortRequest inValue = new FirmElect.Bus.Java.SetParametroProxyPortRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyPortRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyPortAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse FirmElect.Bus.Java.EFirm.SetParametroUrlWSRecepcion(FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest request) {
            return base.Channel.SetParametroUrlWSRecepcion(request);
        }
        
        public string SetParametroUrlWSRecepcion(string arg0) {
            FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest inValue = new FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroUrlWSRecepcion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse> FirmElect.Bus.Java.EFirm.SetParametroUrlWSRecepcionAsync(FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest request) {
            return base.Channel.SetParametroUrlWSRecepcionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSRecepcionResponse> SetParametroUrlWSRecepcionAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest inValue = new FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroUrlWSRecepcionRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroUrlWSRecepcionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroAmbienteResponse FirmElect.Bus.Java.EFirm.SetParametroAmbiente(FirmElect.Bus.Java.SetParametroAmbienteRequest request) {
            return base.Channel.SetParametroAmbiente(request);
        }
        
        public string SetParametroAmbiente(string arg0) {
            FirmElect.Bus.Java.SetParametroAmbienteRequest inValue = new FirmElect.Bus.Java.SetParametroAmbienteRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroAmbienteRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroAmbienteResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroAmbiente(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroAmbienteResponse> FirmElect.Bus.Java.EFirm.SetParametroAmbienteAsync(FirmElect.Bus.Java.SetParametroAmbienteRequest request) {
            return base.Channel.SetParametroAmbienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroAmbienteResponse> SetParametroAmbienteAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroAmbienteRequest inValue = new FirmElect.Bus.Java.SetParametroAmbienteRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroAmbienteRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroAmbienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroProxyPassResponse FirmElect.Bus.Java.EFirm.SetParametroProxyPass(FirmElect.Bus.Java.SetParametroProxyPassRequest request) {
            return base.Channel.SetParametroProxyPass(request);
        }
        
        public string SetParametroProxyPass(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyPassRequest inValue = new FirmElect.Bus.Java.SetParametroProxyPassRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyPassRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroProxyPassResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyPass(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPassResponse> FirmElect.Bus.Java.EFirm.SetParametroProxyPassAsync(FirmElect.Bus.Java.SetParametroProxyPassRequest request) {
            return base.Channel.SetParametroProxyPassAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyPassResponse> SetParametroProxyPassAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyPassRequest inValue = new FirmElect.Bus.Java.SetParametroProxyPassRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyPassRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyPassAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroProxyUrlResponse FirmElect.Bus.Java.EFirm.SetParametroProxyUrl(FirmElect.Bus.Java.SetParametroProxyUrlRequest request) {
            return base.Channel.SetParametroProxyUrl(request);
        }
        
        public string SetParametroProxyUrl(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyUrlRequest inValue = new FirmElect.Bus.Java.SetParametroProxyUrlRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyUrlRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroProxyUrlResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyUrl(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUrlResponse> FirmElect.Bus.Java.EFirm.SetParametroProxyUrlAsync(FirmElect.Bus.Java.SetParametroProxyUrlRequest request) {
            return base.Channel.SetParametroProxyUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroProxyUrlResponse> SetParametroProxyUrlAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroProxyUrlRequest inValue = new FirmElect.Bus.Java.SetParametroProxyUrlRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroProxyUrlRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroProxyUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse FirmElect.Bus.Java.EFirm.SetParametroUrlWSAutorizacion(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest request) {
            return base.Channel.SetParametroUrlWSAutorizacion(request);
        }
        
        public string SetParametroUrlWSAutorizacion(string arg0) {
            FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest inValue = new FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequestBody();
            inValue.Body.arg0 = arg0;
            FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse retVal = ((FirmElect.Bus.Java.EFirm)(this)).SetParametroUrlWSAutorizacion(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse> FirmElect.Bus.Java.EFirm.SetParametroUrlWSAutorizacionAsync(FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest request) {
            return base.Channel.SetParametroUrlWSAutorizacionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FirmElect.Bus.Java.SetParametroUrlWSAutorizacionResponse> SetParametroUrlWSAutorizacionAsync(string arg0) {
            FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest inValue = new FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequest();
            inValue.Body = new FirmElect.Bus.Java.SetParametroUrlWSAutorizacionRequestBody();
            inValue.Body.arg0 = arg0;
            return ((FirmElect.Bus.Java.EFirm)(this)).SetParametroUrlWSAutorizacionAsync(inValue);
        }
    }
}
